version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2019-09-11T19-53-16Z
    volumes:
      - data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

volumes:
  data:
